language: go

go:
- 1.15.x

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.33.0

go_import_path: github.com/roflanKisel/cart-go

script:
  - make lint test
  - docker build -t roflanKisel/cart-go .
